[package]
name = "rustcraft"
version = "0.1.0"
edition = "2021"

[features]
big_ids=[] # Increases the potential values of block ids to 2^24

[dependencies.bevy]
version = "0.11.3"

[dependencies.semver]
version = "1.0.20"